# Generated by Django 5.1.4 on 2025-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('story', models.TextField()),
                ('impact', models.TextField()),
                ('founded_year', models.IntegerField()),
                ('people_helped', models.IntegerField()),
                ('active_projects', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
