# Generated by Django 5.1.4 on 2025-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_donation_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
