# Generated by Django 5.1.4 on 2025-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0009_blogpost_likes_comment_likes_comment_parent_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
