# Generated by Django 5.1.4 on 2025-03-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('one-time', 'One-Time'), ('major', 'Major')], max_length=10),
        ),
    ]
